# version: "3"
# services:
#   web-frontend:
#     image: web-image
#     ports:
#     - 8000:8000




version: '3.7'

services:
  app:
    container_name: web
    image: web-image
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/usr/src/app/app/staticfiles
      - media_volume:/usr/src/app/app/mediafiles

volumes:
  static_volume:
  media_volume:

