version: '3.7'

services:
  app:
    container_name: web
    build: ./web
    restart: always
    command: > 
      daphne app.asgi:application --bind 0.0.0.0 --port 8000
    expose:
      - 8000
    volumes:
      - static_volume:/usr/src/app/app/staticfiles
      - media_volume:/usr/src/app/app/mediafiles

volumes:
  static_volume:
  media_volume: